language: java
script:
  - mvn clean package -B -f user-api/pom.xml -DskipTests=true -Pprod
  - docker-compose up -d
  - mvn verify -B -f aceptancetest/pom.xml
  - docker-compose down
install:
  - mvn install -B -f user-api/pom.xml
notifications:
  email:
    recipients:
      - williamfincatti.dasilva@gmail.com
    on_success: never
    on_failure: always