server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://${HOST_MY_SQL:localhost}:3306/user_db
    username: ${USER_NAME_MY_SQL}
    password: ${PASSWORD_MY_SQL}
  jpa:
    hibernate:
      ddl-auto: update
